version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: gais
      POSTGRES_PASSWORD: sbpoteto
      POSTGRES_DB: gais_db_production

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/gais"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://gais:sbpoteto@db:5432/gais_db_production
